config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "home", to: "home#index"
  resources :clients do
    get :trainings, on: :member
  end
  resources :instructors do
    get :trainings, on: :member
  end
  resources :personal_trainings
  root "home#index"  
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :personal_trainings
  validates :phone, presence: true, uniqueness: true, format: { 
    with: /\A(?:\+7|8)[\s-]?(?:\(?\d{3}\)?[\s-]?)\d{3}[\s-]?\d{2}[\s-]?\d{2}\z/,
    message: "must be a valid phone number (10-15 digits, can include a leading '+')" 
  }

  validates :email, presence: true, uniqueness: true, format: { 
    with: /\A[\w+_.\-]+@[a-zA-Z.\-]+\.[a-zA-Z]{2,}\z/,
    message: "must be a valid email address" 
  }

  validates :fullname, presence: true, uniqueness: true, format: {
     with: /\A([A-Za-zА-Яа-я]+(?: [A-Za-zА-Яа-я]+){1,2})\z/, 
     message: "must be two or three words without numbers" 
  }
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  has_many :personal_trainings
  validates :fullname, presence: true, uniqueness: true, format: {
    with: /\A([A-Za-zА-Яа-я]+(?: [A-Za-zА-Яа-я]+){1,2})\z/, 
    message: "must be two or three words without numbers" 
 }
end

app/models/personal_training.rb
class PersonalTraining < ApplicationRecord
  belongs_to :client
  belongs_to :instructor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy trainings]
  rescue_from ActiveRecord::RecordNotUnique, with: :rescue_unique_ex
  def index
    @clients = Client.all
  end

  def show
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to @client
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @client.update(client_params)
      redirect_to @client
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @client.destroy
    redirect_to clients_path
  end

  def trainings
    @trainings = @client.personal_trainings
  end

  private
    def rescue_unique_ex(exception)
      @error_message = "The client with the same email already exists"
      puts ("EXCEPTION CATCHED")
      puts (exception.message)
      render :new
    end

    def set_client
      @client = Client.find(params[:id])
    end

    def client_params
      params.expect(client: [ :fullname, :birthday, :phone, :email ])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: %i[ show edit update destroy trainings]
  def index
    @instructors = Instructor.all
  end

  def show
  end

  def new
    @instructor = Instructor.new
  end

  def create
    @instructor = Instructor.new(instructor_params)
    if @instructor.save
      redirect_to @instructor
    else
      render :new, status: :unprocessible_entity
    end
  end

  def edit
  end

  def update
    if @instructor.update(instructor_params)
      redirect_to @instructor
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @instructor.destroy
    redirect_to instructors_path
  end

  def trainings
    @trainings = @instructor.personal_trainings
  end

  private
  def set_instructor
    @instructor = Instructor.find(params[:id])
  end

  def instructor_params
    params.expect(instructor: [ :fullname, :experience, :qualification ])
  end
end

app/controllers/personal_trainings_controller.rb
class PersonalTrainingsController < ApplicationController
  before_action :set_training, only: %i[ show edit update destroy ]
  before_action :set_clients_and_instructors, only: %i[new edit]
  def index
    @personal_trainings = PersonalTraining.includes(:client, :instructor).all
  end

  def show
  end

  def new
    @personal_training = PersonalTraining.new
  end

  def create
    @personal_training = PersonalTraining.new(personal_training_params)
    if @personal_training.save
      redirect_to @personal_training
    else
      render :new, status: :unprocessible_entity
    end
  end

  def edit
  end

  def update
    if @personal_training.update(personal_training_params)
      redirect_to @personal_training
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @personal_training.destroy
    redirect_to personal_trainings_path
  end

  private
  def set_training
    @personal_training = PersonalTraining.find(params[:id])
  end

  def personal_training_params
    params.expect(personal_training: [ :client_id, :instructor_id, :price, :duration, :schedule ])
  end

  def set_clients_and_instructors
    @clients = Client.all
    @instructors = Instructor.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/personal_trainings_helper.rb
module PersonalTrainingsHelper
end

app/views/clients/_form.html.erb
<div class="page_wrapper">
    <div class="form_wrapper"><%= form_with model: client do |form| %>
        <% if client.errors.any? %>
            <div class="errors">
                <ul>
                    <% client.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>
        <div>
            <%= form.label :fullname %>
            <%= form.text_field :fullname %>
        </div>
        <div>
            <%= form.label :birthday %>
            <%= form.date_field :birthday %>
        </div>
        <div>
            <%= form.label :phone %>
            <%= form.telephone_field :phone %>
        </div>
        <div>
            <%= form.label :email %>
            <%= form.email_field :email %>
        </div>

        <div>
            <%= form.submit %>
        </div>
    </div>
    <% end %>
</div>

app/views/clients/edit.html.erb
<div class="page_wrapper">
    <h1>Edit client</h1>

    <%= render "form", client: @client, error_message: @error_message %>
    <p class="link"><%= link_to "Cancel", @client %></p>
</div>

app/views/clients/index.html.erb
<div class="page_wrapper">
    <h1>Clients</h1>

    <div class="link"> <%= link_to "Add new client", new_client_path %></div>
    <br>
    <div id="clients">
        <% @clients.each do |client|%>
            <div class="link">
                <%= link_to client.fullname, client %>
            </div>
            <br>
        <% end %>
    </div>

    <div class="link"><%= link_to "Home page", home_path %></div>
</div>

app/views/clients/new.html.erb
<div class="page_wrapper">
    <h1>New client</h1>

    <%= render "form", client: @client %>
    <p class="link"><%= link_to "Cancel", clients_path %></p>
</div>

app/views/clients/show.html.erb
<div class="page_wrapper">
    <h1><%= @client.fullname %></h1>
    <div class="attr_wrapper">
        <p class="attr_title">birthday:</p>
        <div class="attr_data">
            <%= @client.birthday%>
        </div>
    </div>
    <div class="attr_wrapper">
        <p class="attr_title">phone:</p>
        <div class="attr_data">
            <%= @client.phone%>
        </div>
    </div>
    <div class="attr_wrapper">
        <p class="attr_title">email:</p>
        <div class="attr_data">
            <%= @client.email%>
        </div>
    </div>
    <p class="link"><%= link_to "Back", clients_path %></p>
    <p class="link"><%= link_to "Edit", edit_client_path(@client) %></p>
    <p class="link"><%= link_to 'View Trainings', trainings_client_path(@client) %></p>
    <p><%= button_to "Delete", @client, method: :delete, data: { turbo_confirm: "All of the data about this client will be deleted. Are you sure?"} %></p>
</div>

app/views/clients/trainings.html.erb
<div class="page_wrapper">
  <h1>Все тренировки для <%= @client.fullname %></h1>

  <% if @trainings.any? %>
    <table>
      <thead>
        <tr>
          <th class="data_cell">Schedule</th>
          <th class="data_cell">Instructor</th>
          <th class="data_cell">Price</th>
          <th class="data_cell">Duration</th>
        </tr>
      </thead>
      <tbody>
        <% @trainings.each do |training| %>
          <tr>
            <td class="data_cell"><%= training.schedule %></td>
            <td class="data_cell"><%= training.instructor.fullname %></td>
            <td class="data_cell"><%= training.price %></td>
            <td class="data_cell"><%= training.duration %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>This client has no personal trainings.</p>
  <% end %>

  <div class="link">
    <%= link_to 'Back to Client', clients_path %>
  </div>
</div>

app/views/home/index.html.erb
<div class="page_wrapper">
    <h1>Gym Forged</h1>
    <div class="link_wrapper">
        <div class="link"><%= link_to "Clients", clients_path %></div>
        <div class="link"><%= link_to "Instructors", instructors_path %></div>
        <div class="link"><%= link_to "Personal Trainings", personal_trainings_path %></div>
    </div>
</div>

app/views/instructors/_form.html.erb
<div class="page_wrapper">
    <div class="form_wrapper"><%= form_with model: instructor do |form| %>
        <div>
            <%= form.label :fullname %>
            <%= form.text_field :fullname %>
        </div>
        <div>
            <%= form.label :experience %>
            <%= form.number_field :experience, min: 1, max: 40, step: 1%>
        </div>
        <div>
            <%= form.label :qualification %>
            <%= form.text_field :qualification %>
        </div>

        <div>
            <%= form.submit %>
        </div>
    </div>
    <% end %>
</div>

app/views/instructors/edit.html.erb
<div class="page_wrapper">
    <h1>Edit instructor</h1>

    <%= render "form", instructor: @instructor %>
    <p class="link"><%= link_to "Cancel", @instructor %></p>
</div>

app/views/instructors/index.html.erb
<div class="page_wrapper">
    <h1>Instructors</h1>

    <div class="link"><%= link_to "Add new instructor", new_instructor_path %></div>
    <br>
    <div id="instructors">
        <% @instructors.each do |instructor|%>
            <div class="link">
                <%= link_to instructor.fullname, instructor %>
            </div>
            <br>
        <% end %>
    </div>

    <div class="link"><%= link_to "Home page", home_path %></div>
</div>

app/views/instructors/new.html.erb
<div class="page_wrapper">
    <h1>New instructor</h1>

    <%= render "form", instructor: @instructor %>
    <p class="link"><%= link_to "Cancel", instructors_path %></p>
</div>

app/views/instructors/show.html.erb
<div class="page_wrapper">
    <h1><%= @instructor.fullname %></h1>

    <div class=attr_wrapper>
        <p class="attr_title">experience:</p>
        <div class="attr_data">
            <%= @instructor.experience%>
        </div>
    </div>
    <div class=attr_wrapper>
        <p class="attr_title">qualification:</p>
        <div class="attr_data">
            <%= @instructor.qualification%>
        </div>
    </div>
    <p class="link"><%= link_to "Back", instructors_path %></p>
    <p class="link"><%= link_to "Edit", edit_instructor_path(@instructor) %></p>
    <p class="link"><%= link_to 'View Trainings', trainings_instructor_path(@instructor) %></p>
    <p><%= button_to "Delete", @instructor, method: :delete, data: { turbo_confirm: "All of the data about this instructor will be deleted. Are you sure?"} %></p>
</div>

app/views/instructors/trainings.html.erb
<div class="page_wrapper">
  <h1>Тренировки для <%= @instructor.fullname %></h1>

  <% if @trainings.any? %>
    <table>
      <thead>
        <tr>
          <th class="data_cell">Schedule</th>
          <th class="data_cell">Instructor</th>
          <th class="data_cell">Price</th>
          <th class="data_cell">Duration</th>
        </tr>
      </thead>
      <tbody>
        <% @trainings.each do |training| %>
          <tr>
            <td class="data_cell"><%= training.schedule %></td>
            <td class="data_cell"><%= training.client.fullname %></td>
            <td class="data_cell"><%= training.price %></td>
            <td class="data_cell"><%= training.duration %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>This instructor has no personal trainings.</p>
  <% end %>
  <br>
  <div class="link">
    <%= link_to 'Back to Instructors', instructors_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Gym Forged" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/personal_trainings/_form.html.erb
<div class="page_wrapper">
    <div class="form_wrapper"><%= form_with model: personal_training do |form| %>
        <div>
            <%= form.label :client_id %>
            <%= form.collection_select :client_id, @clients, :id, :fullname, prompt: "Select a Client" %>
        </div>
        <div>
            <%= form.label :instructor_id %>
            <%= form.collection_select :instructor_id, @instructors, :id, :fullname, prompt: "Select an Instructor" %>
        </div>
        <div>
            <%= form.label :price %>
            <%= form.number_field :price%>
        </div>
        <div>
            <%= form.label :duration %>
            <%= form.number_field :duration %>
        </div>
        <div>
            <%= form.label :schedule %>
            <%= form.datetime_field :schedule %>
        </div>

        <div>
            <%= form.submit %>
        </div>
    </div>
    <% end %>
</div>

app/views/personal_trainings/edit.html.erb
<div class="page_wrapper">
    <h1>Edit personal_training</h1>

    <%= render "form", personal_training: @personal_training %>
    <p class="link"><%= link_to "Cancel", @personal_training %></p>
</div>

app/views/personal_trainings/index.html.erb
<div class="page_wrapper">
    <h1>Personal Trainings</h1>

    <div class="link"><%= link_to "Add new training", new_personal_training_path %></div>
    <br>
    <div id="trainings">
        <% @personal_trainings.each do |personal_training|%>
            <div class="link">
                <%= link_to personal_training do %>
                    <div>
                        <%=personal_training.schedule%>
                        <%=personal_training.client.fullname%>
                        |
                        <%=personal_training.instructor.fullname%>
                    </div>
                <% end %>
            </div>
            <br>
        <% end %>
    </div>

    <div class="link"><%= link_to "Home page", home_path %></div>
</div>

app/views/personal_trainings/new.html.erb
<div class="page_wrapper">
    <h1>New personal_training</h1>

    <%= render "form", personal_training: @personal_training %>
    <p class="link"><%= link_to "Cancel", personal_trainings_path %></p>
</div>

app/views/personal_trainings/show.html.erb
<div class="page_wrapper">
    <h1><%= @personal_training.schedule %></h1>
    <div class="attr_wrapper">
        <p class="attr_title">client_fullname:</p>
        <div class="attr_data">
            <%= @personal_training.client.fullname%>
        </div>
    </div>
    <div class="attr_wrapper">
        <p class="attr_title">instructor_fullname:</p>
        <div class="attr_data">
            <%= @personal_training.instructor.fullname%>
        </div>
    </div>
    <div class="attr_wrapper">
        <p class="attr_title">price:</p>
        <div class="attr_data">
            <%= @personal_training.price%>
        </div>
    </div>
    <div class="attr_wrapper">
        <p class="attr_title">duration:</p>
        <div class="attr_data">
            <%= @personal_training.duration%>
        </div>
    </div>
    <div class="attr_wrapper">
        <p class="attr_title">schedule:</p>
        <div class="attr_data">
            <%= @personal_training.schedule%>
        </div>
    </div>
    <p class="link"><%= link_to "Back", personal_trainings_path %></p>
    <p class="link"><%= link_to "Edit", edit_personal_training_path(@personal_training) %></p>
    <p><%= button_to "Delete", @personal_training, method: :delete, data: { turbo_confirm: "All of the data about this personal_training will be deleted. Are you sure?"} %></p>
</div>